#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_APP_PROJECT_INFO_PRESENT
#define SL_CATALOG_GECKO_BOOTLOADER_INTERFACE_PRESENT
#define SL_CATALOG_TRUSTZONE_SECURE_CONFIG_PRESENT
#define SL_CATALOG_EMLIB_CORE_PRESENT
#define SL_CATALOG_EMLIB_RMU_PRESENT
#define SL_CATALOG_INTERRUPT_MANAGER_PRESENT
#define SL_CATALOG_MEMORY_MANAGER_PRESENT
#define SL_CATALOG_SE_MANAGER_PRESENT
#define SL_CATALOG_SL_CORE_PRESENT
#define SL_CATALOG_FTP_PRESENT
#define SL_CATALOG_MEMPOOL_PRESENT
#define SL_CATALOG_WISUN_APP_BRD_FEATURE_PRESENT
#define SL_CATALOG_WISUN_APP_CORE_PRESENT
#define SL_CATALOG_WISUN_COAP_PRESENT
#define SL_CATALOG_WISUN_EVENT_MGR_PRESENT
#define SL_CATALOG_FTP_WISUN_POSIX_PORT_PRESENT
#define SL_CATALOG_WISUN_FULL_CONFIG_PRESENT
#define SL_CATALOG_WISUN_OTA_DFU_PRESENT
#define SL_CATALOG_WISUN_TRACE_UTIL_PRESENT
#define SL_CATALOG_SLEEPTIMER_PRESENT
#define SL_CATALOG_WISUN_CONFIG_PRESENT

#endif // SL_COMPONENT_CATALOG_H
